#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2022 darkfrank-it

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the 
# Free Software Foundation, version 3.

# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# ImageMagick is needed to draw copyright string to picture
# identify | head -1

# $bing is needed to form the fully qualified URL for
# the Bing pic of the day
bing="www.bing.com"

# $xmlURL is needed to get the xml data from which
# the relative URL for the Bing pic of the day is extracted
#
# The mkt parameter determines which Bing market you would like to
# obtain your images from.
# Valid values are: en-US, zh-CN, ja-JP, en-AU, en-UK, de-DE, en-NZ, en-CA.
#
# The idx parameter determines where to start from. 0 is the current day,
# 1 the previous day, etc.
xmlURL="http://www.bing.com/HPImageArchive.aspx?format=xml&idx=0&n=1&mkt=it-IT"

# $saveDir is used to set the location where Bing pics of the day
# are stored. $HOME holds the path of the current user's home directory
saveDir='/usr/local/share/'

# Create saveDir if it does not already exist
mkdir -p $saveDir

# The desired Bing picture resolution to download
# Valid options: "_1024x768" "_1280x720" "_1366x768" "_1920x1200"
#picRes="_1920x1200"

# The file extension for the Bing pic
#picExt=".jpg"

# Extract the relative URL of the Bing pic of the day from
# the XML data retrieved from xmlURL, form the fully qualified
# URL for the pic of the day, and store it in $picURL
xmlFile=$(curl -s $xmlURL)
#picURL=$bing$(echo $xmlFile | grep -oP "<urlBase>(.*)</urlBase>" | cut -d ">" -f 2 | cut -d "<" -f 1)$picRes$picExt
picURL=$bing$(echo $xmlFile | grep -oP "<url>(.*)</url>" | cut -d ">" -f 2 | cut -d "<" -f 1)
picDesc=$(echo $xmlFile | grep -oP "<copyright>(.*)</copyright>" | cut -d ">" -f 2 | cut -d "<" -f 1)

# $picName contains the filename of the Bing pic of the day
picName=$(echo $picURL | cut -d "=" -f 2 | cut -d "&" -f 1)

# Download the Bing pic of the day
curl --create-dirs -s -o $saveDir$picName $picURL
BACK_PID=$!
wait $BACK_PID

# Set the sddm wallpaper
cp -f $saveDir$picName /usr/share/sddm/themes/lubuntu/wall.png
convert -font helvetica -fill "rgba(255,255,255,0.80)" -pointsize 30 -draw "text 1300,80 '$picDesc'" /usr/share/sddm/themes/lubuntu/wall.png /usr/share/sddm/themes/lubuntu/wall.png

# Remove pictures older than 7 days
find $saveDir -atime 7 -delete

# Exit the script
exit
