#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2022 darkfrank-it

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the 
# Free Software Foundation, version 3.

# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# ImageMagick is needed to draw copyright string to picture
# It can be disabled (so ImageMagick is not needed) by putting picCopyright to false
# identify | head -1

# $bing is needed to form the fully qualified URL for
# the Bing pic of the day
bing="www.bing.com"

# Set default values
#
# The mkt parameter determines which Bing market you would like to
# obtain your images from.
# Valid values are: en-US, zh-CN, ja-JP, en-AU, en-UK, de-DE, en-NZ, en-CA, it-IT.
mktValue=$(echo $LANG | cut -d "." -f 1 | tr _ -)

# $saveDir is used to set the location where Bing pics of the day
# are stored. $HOME holds the path of the current user's home directory
# The images will be saved in  $saveDir
saveDir='/usr/local/share/sddm-bing-pod/'

# The desired Bing picture resolution to download
# Valid options: "_1024x768" "_1280x720" "_1366x768" "_1920x1080"
picRes="_1920x1080"

# The desired size of overlay text
# Recommend options: "22" "24" "26" "28"
pointSize="28"

# The file extension for the Bing pic
picExt=".jpg"

# Print to image the copyright information that describe the image
# Valid options: "true", "false"
picCopyright=true

# Remove picture older than $picRemoveOld located into $saveDir
# Valid options: "-1": never remove, "1" remove 1 day old picture, "2" remove 2 day old picture and so on 
picRemoveOld=7

# The location of settings file
appConfDir=/etc/sddm-bing-pod/
if [ -f ${appConfDir}settings ] ; then
  . ${appConfDir}settings
fi

# $xmlURL is needed to get the xml data from which
# the relative URL for the Bing pic of the day is extracted
# The idx parameter determines where to start from. 0 is the current day,
# 1 the previous day, etc.
xmlURL="http://www.bing.com/HPImageArchive.aspx?format=xml&idx=0&n=1&mkt=$mktValue"

# Create saveDir if it does not already exist
mkdir -p $saveDir

# Extract the relative URL of the Bing pic of the day from
# the XML data retrieved from xmlURL, form the fully qualified
# URL for the pic of the day, and store it in $picURL
xmlFile=$(curl -s $xmlURL)
picURL=$bing$(echo $xmlFile | grep -oP "<urlBase>(.*)</urlBase>" | cut -d ">" -f 2 | cut -d "<" -f 1)$picRes$picExt
# picURL=$bing$(echo $xmlFile | grep -oP "<url>(.*)</url>" | cut -d ">" -f 2 | cut -d "<" -f 1)

# $picName contains the filename of the Bing pic of the day
picName=$(echo $picURL | cut -d "=" -f 2 | cut -d "&" -f 1)

# Download the Bing pic of the day
if [ ! -f $saveDir$picName ] ; then
  curl --create-dirs -s -o $saveDir$picName $picURL
  BACK_PID=$!
  wait $BACK_PID
fi

# Set the sddm wallpaper
cp -f $saveDir$picName /usr/share/sddm/themes/lubuntu/wall.png
if [ "$picCopyright" = true ] ; then
  picDesc=$(echo $xmlFile | grep -oP "<copyright>(.*)</copyright>" | cut -d ">" -f 2 | cut -d "<" -f 1)
  convert -font helvetica -fill "rgba(255,255,255,0.80)" -pointsize $pointSize -draw "gravity SouthEast text 30,50 '$picDesc'" /usr/share/sddm/themes/lubuntu/wall.png /tmp/wall.png
  mv -f /tmp/wall.png /usr/share/sddm/themes/lubuntu/wall.png
fi

# Remove pictures older than 7 days
if [ "$picRemoveOld" != "-1" ] ; then
  find $saveDir -atime $picRemoveOld -delete
fi

# Exit the script
exit
